<?php

namespace App\Services;

use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use App\Models\ProductStatus;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class OrderService
{
    /**
     * Create a new order with items
     * Replaces legacy processOrder() function
     *
     * @param User $user
     * @param array $items Array of ['product_id' => int, 'quantity' => int]
     * @return Order
     * @throws \Exception
     */
    public function createOrder(User $user, array $items): Order
    {
        return DB::transaction(function () use ($user, $items) {
            // Create order (order_number auto-generated by model event)
            $order = Order::create([
                'user_id' => $user->user_id,
                'status_id' => ProductStatus::PENDING,
                'total_amount' => 0, // Will be calculated
            ]);

            $totalAmount = 0;

            foreach ($items as $item) {
                // Lock product for update to prevent race conditions
                $product = Product::lockForUpdate()->findOrFail($item['product_id']);

                // Check stock availability (if implementing inventory tracking)
                // Uncomment if needed:
                // if ($product->stock_quantity < $item['quantity']) {
                //     throw new \Exception("สินค้า {$product->product_name} มีไม่เพียงพอ");
                // }

                // Calculate subtotal
                $quantity = (int) $item['quantity'];
                $unitPrice = $product->price;
                $subtotal = $unitPrice * $quantity;

                // Create order detail
                OrderDetail::create([
                    'order_id' => $order->order_id,
                    'product_id' => $product->product_id,
                    'product_number' => $product->product_number,
                    'quantity' => $quantity,
                    'unit_price' => $unitPrice,
                    'subtotal' => $subtotal,
                ]);

                // Update stock (if implementing inventory)
                // $product->decrement('stock_quantity', $quantity);

                $totalAmount += $subtotal;
            }

            // Update order total
            $order->update(['total_amount' => $totalAmount]);

            // Log order creation
            Log::channel('security')->info('Order created', [
                'order_id' => $order->order_id,
                'order_number' => $order->order_number,
                'user_id' => $user->user_id,
                'total_amount' => $totalAmount,
                'items_count' => count($items),
            ]);

            return $order->fresh(['orderDetails.product', 'status']);
        });
    }

    /**
     * Update order items (only for PENDING orders)
     * Replaces legacy updateOrderItems() function
     *
     * @param Order $order
     * @param array $items
     * @return Order
     * @throws \Exception
     */
    public function updateOrder(Order $order, array $items): Order
    {
        // Verify order is still pending
        if ($order->status_id !== ProductStatus::PENDING) {
            throw new \Exception('ไม่สามารถแก้ไขออเดอร์ที่ยืนยันแล้ว');
        }

        return DB::transaction(function () use ($order, $items) {
            // Get current order detail IDs
            $currentProductIds = $order->orderDetails->pluck('product_id')->toArray();
            $newProductIds = array_column($items, 'product_id');

            // Delete removed items
            $removedIds = array_diff($currentProductIds, $newProductIds);
            OrderDetail::where('order_id', $order->order_id)
                ->whereIn('product_id', $removedIds)
                ->delete();

            $totalAmount = 0;

            foreach ($items as $item) {
                $product = Product::lockForUpdate()->findOrFail($item['product_id']);
                $quantity = (int) $item['quantity'];
                $unitPrice = $product->price;
                $subtotal = $unitPrice * $quantity;

                // Update or create order detail
                OrderDetail::updateOrCreate(
                    [
                        'order_id' => $order->order_id,
                        'product_id' => $product->product_id,
                    ],
                    [
                        'product_number' => $product->product_number,
                        'quantity' => $quantity,
                        'unit_price' => $unitPrice,
                        'subtotal' => $subtotal,
                    ]
                );

                $totalAmount += $subtotal;
            }

            // Update order total
            $order->update(['total_amount' => $totalAmount]);

            Log::channel('security')->info('Order updated', [
                'order_id' => $order->order_id,
                'order_number' => $order->order_number,
                'user_id' => $order->user_id,
                'new_total' => $totalAmount,
            ]);

            return $order->fresh(['orderDetails.product', 'status']);
        });
    }

    /**
     * Confirm order with shipping address
     * Replaces legacy confirmOrderWithAddress() function
     * 
     * FIXES BUG: Now also updates status to CONFIRMED (legacy code didn't)
     *
     * @param Order $order
     * @param string $shippingAddress
     * @return Order
     * @throws \Exception
     */
    public function confirmOrder(Order $order, string $shippingAddress): Order
    {
        // Verify order is still pending
        if ($order->status_id !== ProductStatus::PENDING) {
            throw new \Exception('ออเดอร์นี้ได้รับการยืนยันแล้ว');
        }

        return DB::transaction(function () use ($order, $shippingAddress) {
            $order->update([
                'shipping_address' => $shippingAddress,
                'status_id' => ProductStatus::CONFIRMED, // BUG FIX: Update status
            ]);

            Log::channel('security')->info('Order confirmed', [
                'order_id' => $order->order_id,
                'order_number' => $order->order_number,
                'user_id' => $order->user_id,
                'total_amount' => $order->total_amount,
            ]);

            return $order->fresh(['orderDetails.product', 'status']);
        });
    }

    /**
     * Bulk confirm orders (admin only)
     * Replaces legacy bulkConfirmOrders() function
     *
     * @param array $orderIds
     * @return int Number of confirmed orders
     */
    public function bulkConfirmOrders(array $orderIds): int
    {
        return DB::transaction(function () use ($orderIds) {
            $count = Order::whereIn('order_id', $orderIds)
                ->where('status_id', ProductStatus::PENDING)
                ->update(['status_id' => ProductStatus::CONFIRMED]);

            Log::channel('security')->info('Bulk order confirmation', [
                'admin_user_id' => auth()->id(),
                'order_ids' => $orderIds,
                'confirmed_count' => $count,
            ]);

            return $count;
        });
    }
}
