FROM php:8.4-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions needed for Laravel
RUN docker-php-ext-install pdo pdo_mysql mysqli zip bcmath

# Set working directory
WORKDIR /app

CMD ["php", "artisan", "migrate:fresh", "--seed"]
